package br.com.systrans.util.constants;

public class MensagemConstants {

	private MensagemConstants() {
	}

	public static final String MENSAGEM_SELECIONE_ESTADO = "MENSAGEM_SELECIONE_ESTADO";
	public static final String MENSAGEM_INSIRA_DESCRICAO_VALIDA = "MENSAGEM_INSIRA_DESCRICAO_VALIDA";

	public static final String MENSAGEM_INSIRA_NOME = "MENSAGEM_INSIRA_NOME";
	public static final String MENSAGEM_SELECIONE_TIPO_CLIENTE = "MENSAGEM_SELECIONE_TIPO_CLIENTE";
	public static final String MENSAGEM_INSIRA_CPF = "MENSAGEM_INSIRA_CPF";
	public static final String MENSAGEM_CPF_INVALIDO = "MENSAGEM_CPF_INVALIDO";
	public static final String MENSAGEM_INSIRA_CNPJ = "MENSAGEM_INSIRA_CNPJ";
	public static final String MENSAGEM_CNPJ_INVALIDO = "MENSAGEM_CNPJ_INVALIDO";
	public static final String MENSAGEM_SELECIONE_CIDADE = "MENSAGEM_SELECIONE_CIDADE";
	public static final String MENSAGEM_INSIRA_ENDERECO = "MENSAGEM_INSIRA_ENDERECO";
	public static final String MENSAGEM_INSIRA_NUMERO = "MENSAGEM_INSIRA_NUMERO";
	public static final String MENSAGEM_INSIRA_BAIRRO = "MENSAGEM_INSIRA_BAIRRO";
	public static final String MENSAGEM_INSIRA_CEP = "MENSAGEM_INSIRA_CEP";
	public static final String MENSAGEM_SELECIONE_SEXO = "MENSAGEM_SELECIONE_SEXO";
	public static final String MENSAGEM_SELECIONE_SITUACAO = "MENSAGEM_SELECIONE_SITUACAO";
	public static final String MENSAGEM_CONFIGURACOES_INVALIDAS = "MENSAGEM_CONFIGURACOES_INVALIDAS";

	public static final String MENSAGEM_INSIRA_UF_VALIDA = "MENSAGEM_INSIRA_UF_VALIDA";

	public static final String MENSAGEM_INSIRA_USUARIO = "MENSAGEM_INSIRA_USUARIO";
	public static final String MENSAGEM_USUARIO_NAO_ENCONTADO = "MENSAGEM_USUARIO_NAO_ENCONTADO";
	public static final String MENSAGEM_SELECIONE_CLIENTE = "MENSAGEM_SELECIONE_CLIENTE";
	public static final String MENSAGEM_CLIENTE_COM_LOGIN = "MENSAGEM_CLIENTE_COM_LOGIN";

	public static final String MENSAGEM_SELECIONE_PERMISSAO_PESQUISA = "MENSAGEM_SELECIONE_PERMISSAO_PESQUISA";
	public static final String MENSAGEM_INSIRA_PAGINACAO_VALIDA = "MENSAGEM_INSIRA_PAGINACAO_VALIDA";
	public static final String MENSAGEM_PEQUISA_VALIDA = "MENSAGEM_PEQUISA_VALIDA";
	public static final String MENSAGEM_SELECIONE_CAMPO_PESQUISA = "MENSAGEM_SELECIONE_CAMPO_PESQUISA";

	public static final String MENSAGEM_SELECIONE_PESQUISA = "MENSAGEM_SELECIONE_PESQUISA";
	public static final String MENSAGEM_SELECIONE_APENAS_UM_REGISTRO = "MENSAGEM_SELECIONE_APENAS_UM_REGISTRO";
	public static final String MENSAGEM_SELECIONE_UM_REGISTRO = "MENSAGEM_SELECIONE_UM_REGISTRO";

	public static final String MENSAGEM_SELECIONE_FIELD = "MENSAGEM_SELECIONE_FIELD";
	public static final String MENSAGEM_SELECIONE_FORMATACAO = "MENSAGEM_SELECIONE_FORMATACAO";
	public static final String MENSAGEM_INSIRA_TAMANHO_VALIDO = "MENSAGEM_INSIRA_TAMANHO_VALIDO";

	public static final String MENSAGENS_PERMISSOES_SALVAS = "MENSAGENS_PERMISSOES_SALVAS";

	public static final String MENSAGEM_ATUALIZAR_VERSAO = "MENSAGEM_ATUALIZAR_VERSAO";
	public static final String MENSAGEM_THREAD_VERSAO_INTEROMPIDA = "MENSAGEM_THREAD_VERSAO_INTEROMPIDA";
	public static final String MENSAGEM_LOG_GERANDO_ARQUIVO = "MENSAGEM_LOG_GERANDO_ARQUIVO";
	public static final String MENSAGEM_LOG_ARQUIVO_DA_VERSAO = "MENSAGEM_LOG_ARQUIVO_DA_VERSAO";
	public static final String MENSAGEM_LOG_VERSAO_NAO_PODE_SER_GERADO = "MENSAGEM_LOG_VERSAO_NAO_PODE_SER_GERADO";

	public static final String MENSAGEM_INSIRA_DATA_ADMISSAO = "MENSAGEM_INSIRA_DATA_ADMISSAO";
	public static final String MENSAGEM_INSIRA_MODALIDADE = "MENSAGEM_INSIRA_MODALIDADE";
	public static final String MENSAGEM_SELECIONE_PROCEDENCIA = "MENSAGEM_SELECIONE_PROCEDENCIA";
	public static final String MENSAGEM_INSIRA_SALARIO = "MENSAGEM_INSIRA_SALARIO";
	public static final String MENSAGEM_INSIRA_CARGO = "MENSAGEM_INSIRA_CARGO";
	public static final String MENSAGEM_FUNCIONARIO_CADASTRADO = "MENSAGEM_FUNCIONARIO_CADASTRADO";
	public static final String MENSAGEM_SELECIONE_GRUPO = "MENSAGEM_SELECIONE_GRUPO";

	public static final String MENSAGEM_INSIRA_RG = "MENSAGEM_INSIRA_RG";
	public static final String MENSAGEM_INSIRA_DATA_NASCIMENTO = "MENSAGEM_INSIRA_DATA_NASCIMENTO";
	public static final String MENSAGEM_DATA_EVOLUCAO_INVALIDA = "MENSAGEM_DATA_EVOLUCAO_INVALIDA";
	public static final String MENSAGEM_EVOLUCAO_NAO_INFORMADA = "MENSAGEM_EVOLUCAO_NAO_INFORMADA";
	public static final String MENSAGEM_INSIRA_NOME_PAI = "MENSAGEM_INSIRA_NOME_PAI";
	public static final String MENSAGEM_INSIRA_NOME_MAE = "MENSAGEM_INSIRA_NOME_MAE";
	public static final String MENSAGEM_SELECIONE_NATURALIDADE = "MENSAGEM_SELECIONE_NATURALIDADE";
	public static final String MENSAGEM_INSIRA_CELULAR = "MENSAGEM_INSIRA_CELULAR";
	public static final String MENSAGEM_INSIRA_EMAIL = "MENSAGEM_INSIRA_EMAIL";
	public static final String MENSAGEM_SELECIONE_ESTADO_CIVIL = "MENSAGEM_SELECIONE_ESTADO_CIVIL";
	public static final String MENSAGEM_SELECIONE_ESCOLARIDADE = "MENSAGEM_SELECIONE_ESCOLARIDADE";
	public static final String MENSAGEM_SELECIONE_RACA = "MENSAGEM_SELECIONE_RACA";
	public static final String MENSAGEM_SELECIONE_RELIGIAO = "MENSAGEM_SELECIONE_RELIGIAO";
	public static final String MENSAGEM_CONFIGURACOES_SALVAS = "MENSAGEM_CONFIGURACOES_SALVAS";
	public static final String MENSAGEM_INSIRA_SENHA = "MENSAGEM_INSIRA_SENHA";
	public static final String MENSAGEM_PROCESSO_INTEROMPIDO_USUARIO = "MENSAGEM_PROCESSO_INTEROMPIDO_USUARIO";
	public static final String MENSAGEM_INSIRA_NUMERO_PARCELAS = "MENSAGEM_INSIRA_NUMERO_PARCELAS";
	public static final String MENSAGEM_INSIRA_VALOR_PARCELAS = "MENSAGEM_INSIRA_VALOR_PARCELAS";
	public static final String MENSAGEM_INSIRA_NUMERO_DIAS = "MENSAGEM_INSIRA_NUMERO_DIAS";
	public static final String MENSAGEM_SELECIONE_FORMA_PAGAMAMENTO = "MENSAGEM_SELECIONE_FORMA_PAGAMAMENTO";
	public static final String MENSAGEM_SELECIONE_TIPO_HISTORICO = "MENSAGEM_SELECIONE_TIPO_HISTORICO";
	public static final String MENSAGEM_SELECIONE_FUNCIONARIO = "MENSAGEM_SELECIONE_FUNCIONARIO";
	public static final String MENSAGEM_INSIRA_CNH = "MENSAGEM_INSIRA_CNH";
	public static final String MENSAGEM_INSIRA_NUMERO_DOCUMENTO = "MENSAGEM_INSIRA_NUMERO_DOCUMENTO";
	public static final String MENSAGEM_INSIRA_DATA_VENCIMENTO = "MENSAGEM_INSIRA_DATA_VENCIMENTO";
	public static final String MENSAGEM_MOTORISTA_CADASTRADO = "MENSAGEM_MOTORISTA_CADASTRADO";
	public static final String MENSAGEM_INSIRA_CODIGO_DOCUMENTO = "MENSAGEM_INSIRA_CODIGO_DOCUMENTO";
	public static final String MENSAGEM_SELECIONE_FORNECEDOR = "MENSAGEM_SELECIONE_FORNECEDOR";
	public static final String MENSAGEM_SELECIONE_HISTORICO = "MENSAGEM_SELECIONE_HISTORICO";
	public static final String MENSAGEM_INSIRA_DATA_MOVIMENTO = "MENSAGEM_INSIRA_DATA_MOVIMENTO";
	public static final String MENSAGEM_INSIRA_VALOR_PARCELA = "MENSAGEM_INSIRA_VALOR_PARCELA";
	public static final String MENSAGEM_SELECIONE_SALDO = "MENSAGEM_SELECIONE_SALDO";
	public static final String MENSAGEM_HISTORICO_OPERACAO_NAO_ENCONTRADO = "MENSAGEM_HISTORICO_OPERACAO_NAO_ENCONTRADO";
	public static final String MENSAGEM_OPERACAO_CADASTRADA = "MENSAGEM_OPERACAO_CADASTRADA";
	public static final String MENSAGEM_SELECIONE_CONTA_CREDORA = "MENSAGEM_SELECIONE_CONTA_CREDORA";
	public static final String MENSAGEM_SELECIONE_CONTA_DEVEDORA = "MENSAGEM_SELECIONE_CONTA_DEVEDORA";
	public static final String MENSAGEM_PAGAMENTOS_MAIOR_FATURAMENTO = "MENSAGEM_PAGAMENTOS_MAIOR_FATURAMENTO";
	public static final String MENSAGEM_SEM_FATURAMENTO_PAGAMENTOS = "MENSAGEM_SEM_FATURAMENTO_PAGAMENTOS";
	public static final String MENSAGEM_SELECIONE_USUARIO = "MENSAGEM_SELECIONE_USUARIO";
	public static final String MENSAGEM_USUARIO_CAIXA_CADASTRADO = "MENSAGEM_USUARIO_CAIXA_CADASTRADO";
	public static final String MENSAGEM_CAIXA_ABERTO = "MENSAGEM_CAIXA_ABERTO";
	public static final String MENSAGEM_USUARIO_SEM_CAIXA = "MENSAGEM_USUARIO_SEM_CAIXA";
	public static final String MENSAGEM_CAIXA_NAO_ENCONTRADO = "MENSAGEM_CAIXA_NAO_ENCONTRADO";
	public static final String MENSAGEM_CAIXA_FECHADO = "MENSAGEM_CAIXA_FECHADO";
	public static final String MENSAGEM_INSIRA_DATA_VENCIMENTO_CONTA = "MENSAGEM_INSIRA_DATA_VENCIMENTO_CONTA";

}
